"""Tests for the Live Map module: gcode parse, time-model, preamble, mapping."""
import numpy as np

from prusa_pa_tuner.gcode_parse import (
    layer_polylines,
    layer_zs,
    parse_gcode,
)
from prusa_pa_tuner.livemap_gen import build_livemap_gcode
from prusa_pa_tuner.livemap_map import _layers_from_pos_z, layer_detail, map_run
from prusa_pa_tuner.livemap_runner import LiveMapRun, _dump_livemap_run, replay_livemap


# A small two-layer square with a perimeter + infill feature on each layer.
# Relative-E (M83), which is the PrusaSlicer-for-Prusa default.
SAMPLE = """; generated by PrusaSlicer 2.8.1
M201 E5000
M204 P2000 T4000
G90
M83
G28
G1 Z0.2 F300
;LAYER_CHANGE
;Z:0.2
;TYPE:External perimeter
G1 X10 Y10 F9000
G1 X20 Y10 E0.5 F1800
G1 X20 Y20 E0.5
G1 X10 Y20 E0.5
G1 X10 Y10 E0.5
;TYPE:Internal infill
G1 X12 Y12 E0.2 F3000
G1 X18 Y18 E0.4
;LAYER_CHANGE
;Z:0.4
G1 Z0.4 F300
;TYPE:External perimeter
G1 X10 Y10 F9000
G1 X20 Y10 E0.5 F1800
G1 X20 Y20 E0.5
G1 X10 Y20 E0.5
G1 X10 Y10 E0.5
"""


def test_parse_layers_features_bbox():
    pg = parse_gcode(SAMPLE)
    assert len(pg.layers) == 2
    assert layer_zs(pg) == [0.2, 0.4]
    assert "External perimeter" in pg.features
    assert "Internal infill" in pg.features
    # square corners 10..20 on both axes
    assert pg.bbox == (10.0, 20.0, 10.0, 20.0)
    # 6 extruding perimeter+infill on L0, 4 perimeter on L1 (the move INTO
    # the start corner has no extrusion -> travel, not counted)
    assert pg.n_extruding == 4 + 2 + 4


def test_parse_relative_extrusion_marks_travel_vs_extrude():
    pg = parse_gcode(SAMPLE)
    # the first move of each layer (G1 X10 Y10 with no E) is a travel
    travels = [m for m in pg.moves if not m.extruding and m.length_mm > 0]
    assert any(abs(m.x1 - 10) < 1e-9 and abs(m.y1 - 10) < 1e-9 for m in travels)
    # every extruding move carries a positive E delta
    assert all(m.e > 0 for m in pg.moves if m.extruding)


def test_time_model_monotonic_and_positive():
    pg = parse_gcode(SAMPLE)
    ts = [m.t_start for m in pg.moves]
    te = [m.t_end for m in pg.moves]
    assert all(b >= a for a, b in zip(ts, ts[1:]))   # non-decreasing starts
    assert all(e >= s for s, e in zip(ts, te))        # end >= start
    assert pg.total_time_s > 0


def test_binning_fallback_without_layer_markers():
    # no ;LAYER_CHANGE -- layers must be inferred from rising extruding-z
    g = """G90
M83
;TYPE:Perimeter
G1 X0 Y0 Z0.2 F6000
G1 X10 Y0 E0.5 F1200
G1 X10 Y10 E0.5
G1 X0 Y0 Z0.4
G1 X10 Y0 E0.5
G1 X10 Y10 E0.5
"""
    pg = parse_gcode(g)
    assert len(pg.layers) == 2
    assert layer_zs(pg) == [0.2, 0.4]


def test_layer_polylines_grouped_by_feature():
    pg = parse_gcode(SAMPLE)
    polys = layer_polylines(pg, 0)
    feats = [p["feature"] for p in polys]
    assert "External perimeter" in feats
    assert "Internal infill" in feats
    # the perimeter polyline traces the 5 square points (start + 4 edges)
    per = next(p for p in polys if p["feature"] == "External perimeter")
    assert len(per["x"]) == len(per["y"]) >= 4


def test_build_livemap_gcode_injects_preamble_and_strips_m334():
    g = "M334 1.2.3.4 9999\nG90\nG1 X1 Y1 E1\n"
    out = build_livemap_gcode(g, udp_host="10.0.0.7", udp_port=8514)
    assert "M334 10.0.0.7 8514" in out
    assert "M331 loadcell_value" in out
    assert "M331 pos_x" in out and "M331 pos_y" in out and "M331 pos_z" in out
    # the stale slicer M334 is removed, not left to override ours
    assert "M334 1.2.3.4 9999" not in out
    # geometry is preserved verbatim
    assert "G1 X1 Y1 E1" in out


def _synthesize_streams(pg, *, fs=120.0, idle_s=2.0, offset=900.0, seed=0):
    """Walk the parsed path on the MODEL's own time grid, after an idle head.

    Using the model's per-move durations makes the synthetic telemetry a
    faithful "perfect" capture, so the cross-check should report ~zero
    divergence. Force = offset + a per-feature constant + noise, so feature
    aggregates differ and the tare must remove the big static offset.
    """
    rng = np.random.default_rng(seed)
    t, X, Y, Z, F = [], [], [], [], []
    m0 = pg.moves[0]
    for i in range(int(idle_s * fs)):
        t.append(i / fs)
        X.append(m0.x0); Y.append(m0.y0); Z.append(m0.z0)
        F.append(offset + rng.normal(0, 0.4))
    tc = idle_s
    for m in pg.moves:
        dur = m.t_end - m.t_start
        if dur <= 0:
            continue
        n = max(1, int(dur * fs))
        feat = pg.features[m.feature_idx] if m.feature_idx >= 0 else ""
        base = offset + (50.0 if feat == "External perimeter" else 20.0 if feat else 0.0)
        for k in range(1, n + 1):
            a = k / n
            t.append(tc + a * dur)
            X.append(m.x0 + (m.x1 - m.x0) * a)
            Y.append(m.y0 + (m.y1 - m.y0) * a)
            Z.append(m.z0 + (m.z1 - m.z0) * a)
            F.append(base + rng.normal(0, 0.4))
        tc += dur
    t = np.array(t); X = np.array(X); Y = np.array(Y); Z = np.array(Z); F = np.array(F)
    return t, X, Y, Z, F


def test_map_run_per_sample_tare_features():
    pg = parse_gcode(SAMPLE)
    t, X, Y, Z, F = _synthesize_streams(pg, offset=900.0)
    # map_run signature: (force_t, force_y, pos_t, pos_x, pos_y_t, pos_y, pos_z_t, pos_z, parsed)
    m = map_run(t, F, t, X, t, Y, t, Z, pg)

    # one point PER loadcell sample (not per move) -> many more than n_extruding
    assert m.s_force.size > pg.n_extruding
    assert m.s_x.size == m.s_force.size == m.s_layer.size

    # snapped onto the gcode path (square 10..20), all finite
    assert np.isfinite(m.s_x).all() and np.isfinite(m.s_force).all()
    assert m.s_x.min() >= 9.5 and m.s_x.max() <= 20.5

    # tare ~ the injected static offset (so loads are deviations from it)
    assert abs(m.tare - 900.0) < 5.0

    # both real layers got samples (pos_z is NOT used -- layers come from gcode)
    for li in range(len(pg.layers)):
        assert np.count_nonzero(m.s_layer == li) > 0

    # feature aggregates separate perimeter (~50) from infill (~20)
    assert "External perimeter" in m.feature_stats
    assert "Internal infill" in m.feature_stats
    assert m.feature_stats["External perimeter"]["p50"] > m.feature_stats["Internal infill"]["p50"]


def test_arclen_scale_is_near_one_when_telemetry_follows_path():
    pg = parse_gcode(SAMPLE)
    t, X, Y, Z, F = _synthesize_streams(pg)
    m = map_run(t, F, t, X, t, Y, t, Z, pg)
    xc = m.cross
    assert xc["available"] is True
    # telemetry IS the gcode path -> arc-length scale ~1, good agreement
    assert abs(xc["time_scale"] - 1.0) < 0.1
    assert xc["agreement"] in ("good", "warn")


def test_layer_detail_emits_ordered_points():
    pg = parse_gcode(SAMPLE)
    t, X, Y, Z, F = _synthesize_streams(pg)
    m = map_run(t, F, t, X, t, Y, t, Z, pg)
    d = layer_detail(m, 0)
    p = d["pts"]
    n = len(p["x"])
    assert n > 0
    assert len(p["y"]) == len(p["f"]) == len(p["feat"]) == len(p["brk"]) == n
    assert d["n_points"] == n
    assert d["polylines"]  # faint backdrop still present


def test_pos_z_staircase_overrides_drifting_arc_length_boundary():
    """The coarse arc-length layer estimate drifts (observed up to ~130 mm of
    path on livemap_1781710258 -- the layer-bleed bug). The pos_z staircase
    must relocate the boundary to the true z step and snap it to the end of
    the travel there, even with a constant MBL offset and 25% junk spikes."""
    n = 4000
    wt = np.linspace(0.0, 40.0, n)
    # coarse (arc-length) estimate puts the boundary at 60% -- drifted late
    wlayer = np.zeros(n, dtype=int)
    wlayer[int(0.6 * n):] = 1
    # ground truth: z steps at 50%, where there is also a travel
    true_b = int(0.5 * n)
    pz = np.where(np.arange(n) < true_b, 0.2, 0.4) + 0.1  # +0.1 = MBL offset
    rng = np.random.default_rng(1)
    junk = rng.random(n) < 0.25
    pz[junk] = 168.0  # encoder/MBL junk spikes
    trav = np.zeros(n, dtype=bool)
    trav[true_b - 5:true_b + 5] = True
    out, diag = _layers_from_pos_z(wt, wlayer, wt, pz, [0.2, 0.4], trav)
    assert out is not None and diag["available"] is True
    assert diag["source"] == "pos_z"
    assert diag["boundaries"][0]["method"] == "pos_z+travel"
    b = int(np.searchsorted(out, 1))
    # boundary lands at the end of the travel run (true_b + 5), not at the
    # drifted 60% mark; allow slack for the median-filter edge
    assert abs(b - (true_b + 5)) <= 30
    # MBL offset was estimated away
    assert abs(diag["offset"] - 0.1) < 0.03


def test_map_run_layers_from_noisy_pos_z():
    """End-to-end: map_run must take its layers from the pos_z staircase even
    when pos_z carries a constant offset plus junk spikes, and must say so in
    the cross-check."""
    pg = parse_gcode(SAMPLE)
    t, X, Y, Z, F = _synthesize_streams(pg)
    rng = np.random.default_rng(2)
    Zn = Z + 0.12
    junk = rng.random(Zn.size) < 0.25
    Zn[junk] = 168.0
    m = map_run(t, F, t, X, t, Y, t, Zn, pg)
    assert m.cross["layer_source"] == "pos_z"
    assert m.layer_diag["available"] is True
    for li in range(len(pg.layers)):
        assert np.count_nonzero(m.s_layer == li) > 0


# One layer, two long parallel infill lines joined by a U-turn -- the shape
# where a force-stream hole used to draw a false connector across the lines.
TURN_GCODE = """G90
M83
;LAYER_CHANGE
;Z:0.2
;TYPE:Internal infill
G1 X0 Y0 Z0.2 F9000
G1 X30 Y0 E1.0 F1800
G1 X30 Y0.4 E0.02
G1 X0 Y0.4 E1.0
"""


def test_force_hole_over_turnaround_breaks_the_line():
    """A ~60 ms force-stream hole spanning the U-turn leaves its bracketing
    samples adjacent in the stream and only ~0.5 mm apart in XY -- the old
    logic drew a straight connector cutting between the lines. The arc-length
    advance over the hole (~1.8 mm around the turn) disagrees with the chord,
    so the mapper must break the line there."""
    pg = parse_gcode(TURN_GCODE)
    t, X, Y, Z, F = _synthesize_streams(pg, fs=240.0)
    # time at which the head reaches the end of line 1 (x = 30)
    t_turn = float(t[np.argmax(X >= 29.999)])
    keep = ~((t > t_turn - 0.05) & (t < t_turn + 0.05))
    m = map_run(t[keep], F[keep], t, X, t, Y, t, Z, pg)
    assert m.cross["n_hole_breaks"] >= 1
    # no drawn connector crosses between the two lines: every non-break step
    # stays under half the line spacing in y
    dy = np.abs(np.diff(m.s_y))
    conn = ~m.s_brk[1:]
    assert dy[conn].max() < 0.2


def test_pos_pileup_drops_untrusted_samples():
    """Two pos_y timestamps squeezed ~0.1 ms apart (the seam of overlapping
    UDP batches) make interpolated positions laterally wrong nearby; those
    force samples must be dropped and counted."""
    pg = parse_gcode(SAMPLE)
    t, X, Y, Z, F = _synthesize_streams(pg)
    ty = t.copy()
    k = int(0.6 * len(ty))
    ty[k] = ty[k - 1] + 1e-4  # pile-up seam mid-print
    m = map_run(t, F, t, X, ty, Y, t, Z, pg)
    assert m.cross["pos_pile_dropped"] > 0


def test_npz_roundtrip_replay(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    pg = parse_gcode(SAMPLE)
    t, X, Y, Z, F = _synthesize_streams(pg)
    run = LiveMapRun(cfg=None, name="cube.gcode", user_gcode=SAMPLE, parsed=pg)
    run.state.started_at = 1700000000.0
    run.force_t = list(t); run.force_y = list(F)
    run.pos_x_t = list(t); run.pos_x = list(X)
    run.pos_y_t = list(t); run.pos_y = list(Y)
    run.pos_z_t = list(t); run.pos_z = list(Z)

    fname = _dump_livemap_run(run)
    assert fname and fname.startswith("livemap_")
    mapped = replay_livemap(tmp_path / "runs" / fname)
    # re-parsed gcode + re-mapped streams reproduce the layer/feature structure
    assert len(mapped.parsed.layers) == 2
    assert "External perimeter" in mapped.feature_stats
    assert mapped.s_force.size > mapped.parsed.n_extruding
