"""Tests for the Live Map module: gcode parse, time-model, preamble, mapping."""
import numpy as np

from prusa_pa_tuner.gcode_parse import (
    layer_polylines,
    layer_zs,
    parse_gcode,
)
from prusa_pa_tuner.livemap_gen import build_livemap_gcode
from prusa_pa_tuner.livemap_map import layer_detail, map_run
from prusa_pa_tuner.livemap_runner import LiveMapRun, _dump_livemap_run, replay_livemap


# A small two-layer square with a perimeter + infill feature on each layer.
# Relative-E (M83), which is the PrusaSlicer-for-Prusa default.
SAMPLE = """; generated by PrusaSlicer 2.8.1
M201 E5000
M204 P2000 T4000
G90
M83
G28
G1 Z0.2 F300
;LAYER_CHANGE
;Z:0.2
;TYPE:External perimeter
G1 X10 Y10 F9000
G1 X20 Y10 E0.5 F1800
G1 X20 Y20 E0.5
G1 X10 Y20 E0.5
G1 X10 Y10 E0.5
;TYPE:Internal infill
G1 X12 Y12 E0.2 F3000
G1 X18 Y18 E0.4
;LAYER_CHANGE
;Z:0.4
G1 Z0.4 F300
;TYPE:External perimeter
G1 X10 Y10 F9000
G1 X20 Y10 E0.5 F1800
G1 X20 Y20 E0.5
G1 X10 Y20 E0.5
G1 X10 Y10 E0.5
"""


def test_parse_layers_features_bbox():
    pg = parse_gcode(SAMPLE)
    assert len(pg.layers) == 2
    assert layer_zs(pg) == [0.2, 0.4]
    assert "External perimeter" in pg.features
    assert "Internal infill" in pg.features
    # square corners 10..20 on both axes
    assert pg.bbox == (10.0, 20.0, 10.0, 20.0)
    # 6 extruding perimeter+infill on L0, 4 perimeter on L1 (the move INTO
    # the start corner has no extrusion -> travel, not counted)
    assert pg.n_extruding == 4 + 2 + 4


def test_parse_relative_extrusion_marks_travel_vs_extrude():
    pg = parse_gcode(SAMPLE)
    # the first move of each layer (G1 X10 Y10 with no E) is a travel
    travels = [m for m in pg.moves if not m.extruding and m.length_mm > 0]
    assert any(abs(m.x1 - 10) < 1e-9 and abs(m.y1 - 10) < 1e-9 for m in travels)
    # every extruding move carries a positive E delta
    assert all(m.e > 0 for m in pg.moves if m.extruding)


def test_time_model_monotonic_and_positive():
    pg = parse_gcode(SAMPLE)
    ts = [m.t_start for m in pg.moves]
    te = [m.t_end for m in pg.moves]
    assert all(b >= a for a, b in zip(ts, ts[1:]))   # non-decreasing starts
    assert all(e >= s for s, e in zip(ts, te))        # end >= start
    assert pg.total_time_s > 0


def test_binning_fallback_without_layer_markers():
    # no ;LAYER_CHANGE -- layers must be inferred from rising extruding-z
    g = """G90
M83
;TYPE:Perimeter
G1 X0 Y0 Z0.2 F6000
G1 X10 Y0 E0.5 F1200
G1 X10 Y10 E0.5
G1 X0 Y0 Z0.4
G1 X10 Y0 E0.5
G1 X10 Y10 E0.5
"""
    pg = parse_gcode(g)
    assert len(pg.layers) == 2
    assert layer_zs(pg) == [0.2, 0.4]


def test_layer_polylines_grouped_by_feature():
    pg = parse_gcode(SAMPLE)
    polys = layer_polylines(pg, 0)
    feats = [p["feature"] for p in polys]
    assert "External perimeter" in feats
    assert "Internal infill" in feats
    # the perimeter polyline traces the 5 square points (start + 4 edges)
    per = next(p for p in polys if p["feature"] == "External perimeter")
    assert len(per["x"]) == len(per["y"]) >= 4


def test_build_livemap_gcode_injects_preamble_and_strips_m334():
    g = "M334 1.2.3.4 9999\nG90\nG1 X1 Y1 E1\n"
    out = build_livemap_gcode(g, udp_host="10.0.0.7", udp_port=8514)
    assert "M334 10.0.0.7 8514" in out
    assert "M331 loadcell_value" in out
    assert "M331 pos_x" in out and "M331 pos_y" in out and "M331 pos_z" in out
    # the stale slicer M334 is removed, not left to override ours
    assert "M334 1.2.3.4 9999" not in out
    # geometry is preserved verbatim
    assert "G1 X1 Y1 E1" in out


def _synthesize_streams(pg, *, fs=120.0, idle_s=2.0, offset=900.0, seed=0):
    """Walk the parsed path on the MODEL's own time grid, after an idle head.

    Using the model's per-move durations makes the synthetic telemetry a
    faithful "perfect" capture, so the cross-check should report ~zero
    divergence. Force = offset + a per-feature constant + noise, so feature
    aggregates differ and the tare must remove the big static offset.
    """
    rng = np.random.default_rng(seed)
    t, X, Y, Z, F = [], [], [], [], []
    m0 = pg.moves[0]
    for i in range(int(idle_s * fs)):
        t.append(i / fs)
        X.append(m0.x0); Y.append(m0.y0); Z.append(m0.z0)
        F.append(offset + rng.normal(0, 0.4))
    tc = idle_s
    for m in pg.moves:
        dur = m.t_end - m.t_start
        if dur <= 0:
            continue
        n = max(1, int(dur * fs))
        feat = pg.features[m.feature_idx] if m.feature_idx >= 0 else ""
        base = offset + (50.0 if feat == "External perimeter" else 20.0 if feat else 0.0)
        for k in range(1, n + 1):
            a = k / n
            t.append(tc + a * dur)
            X.append(m.x0 + (m.x1 - m.x0) * a)
            Y.append(m.y0 + (m.y1 - m.y0) * a)
            Z.append(m.z0 + (m.z1 - m.z0) * a)
            F.append(base + rng.normal(0, 0.4))
        tc += dur
    t = np.array(t); X = np.array(X); Y = np.array(Y); Z = np.array(Z); F = np.array(F)
    return t, X, Y, Z, F


def test_map_run_per_sample_tare_features():
    pg = parse_gcode(SAMPLE)
    t, X, Y, Z, F = _synthesize_streams(pg, offset=900.0)
    # map_run signature: (force_t, force_y, pos_t, pos_x, pos_y_t, pos_y, pos_z_t, pos_z, parsed)
    m = map_run(t, F, t, X, t, Y, t, Z, pg)

    # one point PER loadcell sample (not per move) -> many more than n_extruding
    assert m.s_force.size > pg.n_extruding
    assert m.s_x.size == m.s_force.size == m.s_layer.size

    # snapped onto the gcode path (square 10..20), all finite
    assert np.isfinite(m.s_x).all() and np.isfinite(m.s_force).all()
    assert m.s_x.min() >= 9.5 and m.s_x.max() <= 20.5

    # tare ~ the injected static offset (so loads are deviations from it)
    assert abs(m.tare - 900.0) < 5.0

    # both real layers got samples (pos_z is NOT used -- layers come from gcode)
    for li in range(len(pg.layers)):
        assert np.count_nonzero(m.s_layer == li) > 0

    # feature aggregates separate perimeter (~50) from infill (~20)
    assert "External perimeter" in m.feature_stats
    assert "Internal infill" in m.feature_stats
    assert m.feature_stats["External perimeter"]["p50"] > m.feature_stats["Internal infill"]["p50"]


def test_arclen_scale_is_near_one_when_telemetry_follows_path():
    pg = parse_gcode(SAMPLE)
    t, X, Y, Z, F = _synthesize_streams(pg)
    m = map_run(t, F, t, X, t, Y, t, Z, pg)
    xc = m.cross
    assert xc["available"] is True
    # telemetry IS the gcode path -> arc-length scale ~1, good agreement
    assert abs(xc["time_scale"] - 1.0) < 0.1
    assert xc["agreement"] in ("good", "warn")


def test_layer_detail_emits_ordered_points():
    pg = parse_gcode(SAMPLE)
    t, X, Y, Z, F = _synthesize_streams(pg)
    m = map_run(t, F, t, X, t, Y, t, Z, pg)
    d = layer_detail(m, 0)
    p = d["pts"]
    n = len(p["x"])
    assert n > 0
    assert len(p["y"]) == len(p["f"]) == len(p["feat"]) == len(p["brk"]) == n
    assert d["n_points"] == n
    assert d["polylines"]  # faint backdrop still present


def test_npz_roundtrip_replay(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    pg = parse_gcode(SAMPLE)
    t, X, Y, Z, F = _synthesize_streams(pg)
    run = LiveMapRun(cfg=None, name="cube.gcode", user_gcode=SAMPLE, parsed=pg)
    run.state.started_at = 1700000000.0
    run.force_t = list(t); run.force_y = list(F)
    run.pos_x_t = list(t); run.pos_x = list(X)
    run.pos_y_t = list(t); run.pos_y = list(Y)
    run.pos_z_t = list(t); run.pos_z = list(Z)

    fname = _dump_livemap_run(run)
    assert fname and fname.startswith("livemap_")
    mapped = replay_livemap(tmp_path / "runs" / fname)
    # re-parsed gcode + re-mapped streams reproduce the layer/feature structure
    assert len(mapped.parsed.layers) == 2
    assert "External perimeter" in mapped.feature_stats
    assert mapped.s_force.size > mapped.parsed.n_extruding
